Add random_seed parameter
nickkunz/smogn pull request #28
Opened 2022-02-25 06:56 UTC by ArnoldYSYeung

Allows user to input a random_seed for repeating runs. If None, does not use random_seed. 
Code has been fixed to apply to every instance of np.random and rd.random. (Seed must be defined prior to every use of np.random and rd.random.)

Code has been tested on `smogn/examples/smogn_example_1_beg.ipynb` . Using the same `random_seed` value always output the same stats.

```
housing_smogn = smogn.smoter(
    
    data = housing,  ## pandas dataframe
    y = 'SalePrice',  ## string ('header name')
    random_seed = 1
)
smogn.box_plot_stats(housing_smogn['SalePrice'])['stats']
```

2022-02-25 06:57 UTC, ArnoldYSYeung commented
@nickkunz The modifications here have been tested with the `smogn/examples/smogn_example_1_beg.ipynb` notebook. Please test with more complex cases as well. Thanks.

2022-03-22 04:33 UTC, Muti23 commented
@ArnoldYSYeung Thanks for your sharing. In fact I also used the same strategy to deal with my problem. I try to implant random seed for several rows in smoter/over_sampling files. Unfortunately it doesn't  solve the problem completely, and only increase the reproducibility of test results. I don't know if you have the same situation? And I will use your modifications to do the same test.

2022-04-04 13:43 UTC, polinamamo commented
@Muti23 my understanding after reading the code, that you need to fix seed for both `np.random.seed(seed)`
    `rd.seed(seed)` at the same time, as both methods are used for random sampling.

2022-04-12 05:41 UTC, nickkunz requested changes
@ArnoldYSYeung can you remove the locally generated pycache files?

2022-04-12 05:44 UTC, nickkunz commented on smogn/over_sampling.py
> +    random_seed = None  ## random seed for sampling (pos int or None)
@ArnoldYSYeung are you open to changing the `random_seed` argument to simply `seed` for brevity?

2022-04-12 05:47 UTC, nickkunz commented
@ArnoldYSYeung @Muti23 @polinamamo thank you all for your input. This is very helpful for everyone using the package.

2022-04-13 05:04 UTC, ArnoldYSYeung commented
@nickkunz Renamed `random_seed` to `seed` and removed pycache files. Please take a look and let me know of any other changes 🙏

2022-05-12 20:31 UTC, nickkunz commented
@ArnoldYSYeung Can we merge this to the `dev` branch before we merging to `master`?

2022-05-12 20:31 UTC, nickkunz approved these changes

2022-05-12 20:33 UTC, nickkunz requested changes
@ArnoldYSYeung Can we merge this to the dev branch before we merging to master?

2022-05-12 20:42 UTC, ArnoldYSYeung commented
@nickkunz Changed base branch from `master` to `dev`

2022-05-12 22:20 UTC, nickkunz approved these changes

2022-05-12 22:25 UTC, nickkunz commented
@ArnoldYSYeung Thank you. I really appreciate your contribution. This needed to be done.

2022-05-12 22:26 UTC, merged